Propagate TX context in Kotlin coroutines
micronaut-projects/micronaut-data pull request #1274
Opened 2022-01-19 09:59 UTC by dstepanov

Fixes #1271
Fixes #1216

2022-01-19 10:05 UTC, graemerocher commented
And what about R2DBC and coroutines?

2022-01-19 11:45 UTC, graemerocher requested changes

2022-01-19 11:45 UTC, graemerocher commented on data-tx/src/main/java/io/micronaut/transaction/interceptor/CoroutineTxHelper.java
> +public final class CoroutineTxHelper {
Does this need to be public?

2022-01-19 11:45 UTC, graemerocher commented on data-tx/src/main/java/io/micronaut/transaction/interceptor/TransactionalInterceptor.java
> +    private final Optional<CoroutineTxHelper> coroutineTxHelper;
Don't store optional fields, just store either the value or null

2022-01-20 06:19 UTC, dstepanov commented
R2dbc TX propagation is a bit complicated, I will try to add it in the future

2022-01-23 14:07 UTC, graemerocher approved these changes

2022-01-24 08:08 UTC, merged