Type-safe queries for Java and Kotlin
micronaut-projects/micronaut-data pull request #1600
Opened 2022-06-30 08:29 UTC by dstepanov

2022-06-30 15:38 UTC, graemerocher requested changes
Looks fine, just a few documentation changes

2022-06-30 15:38 UTC, graemerocher commented on src/main/docs/guide/dbc/dbcCriteriaSpecifications/typeSafeJava.adoc
> +dependency:hibernate-jpamodelgen-jakarta[groupId="org.hibernate"]
add the scope:

```
dependency:hibernate-jpamodelgen-jakarta[groupId="org.hibernate", scope="annotationProcessor"]
```

2022-07-04 09:40 UTC, dstepanov commented
Added Kotlin docs

2022-07-04 09:41 UTC, graemerocher approved these changes

2022-07-04 13:51 UTC, merged