Implement default join alias via `@MappedProperty`
micronaut-projects/micronaut-data pull request #1735
Opened 2022-09-11 03:43 UTC by Goldmensch

closes #1705 

The pr probably contains breaking changes in the query generation if a `@MappedProperty` was already used.

2022-09-11 07:14 UTC, dstepanov requested changes

2022-09-11 07:14 UTC, dstepanov commented on data-processor/src/main/java/io/micronaut/data/processor/visitors/RepositoryTypeElementVisitor.java
> +                if (element.hasAnnotation(JoinSpecifications.class) && !methodMatchContext.hasParameterInRole(TypeRole.PAGEABLE)) {
The logic should be implemented in `AbstractSqlLikeQueryBuilder`: `getAliasName` or `getPathOnlyAliasName`.

2022-09-12 13:06 UTC, dstepanov commented
Please fix the tests

2022-09-12 21:42 UTC, Goldmensch commented
Tests are passing locally, only checkStyle is violated due to the file length fo `SqlQueryBuilder` and `AbstractSqlLikeQueryBuilder`

2022-09-14 05:41 UTC, dstepanov commented
Try to annotate the class with `@SuppressWarnings("FileLength")` try if it passes by running `./gradlew checkstyleMain`

2022-09-14 11:29 UTC, Goldmensch commented
The annotations didn't work, so I added a filename based suppression for the file length check.

2022-09-14 13:09 UTC, dstepanov commented
Thanks!

2022-09-14 13:09 UTC, merged