#1772 accept empty list in CrudRepository.saveAll
micronaut-projects/micronaut-data pull request #1776
Opened 2022-09-30 13:03 UTC by ideadapt

This PR removes the "list not empty" assertion in the base classes AbstractSyncEntitiesOperations and AbstractReactiveEntitiesOperations.
Some implementations of that base classes already had a short circuit to exit early if no work needs to be done because the list is empty.

With this PR the following implementations now accept empty lists:

- MongoReactiveEntitiesOperation (short circuit added in "save all")
- JdbcEntitiesOperations (no short circuit in "save all")
- MongoEntitiesOperation (short circuit existed in "save all")
- R2dbcEntitiesOperations (short circuit existed in "save all")

Related issue #1772

2022-09-30 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-data?pullRequest=1776) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-data?pullRequest=1776) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-data?pullRequest=1776) it.</sub>

2022-10-03 11:42 UTC, radovanradic commented
This looks good to me, but seems like java8 check some tests are failing. Tried to rerun few times, but never completes successfully.

2022-10-03 12:01 UTC, radovanradic commented
> This looks good to me, but seems like java8 check some tests are failing. Tried to rerun few times, but never completes successfully.

And now it just succeeded.

2022-10-03 14:49 UTC, dstepanov requested changes

2022-10-03 16:04 UTC, dstepanov commented
Sonar doesn't run for contributors 😵‍💫

2022-10-03 16:27 UTC, dstepanov commented on data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/AbstractReactiveEntitiesOperations.java
> -        if (!entities.iterator().hasNext()) {
The idea is to avoid unnecessary initialization of the operation object. If you think it's complicated to change, we can leave it as it is.

2022-10-05 08:16 UTC, ideadapt commented on data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/AbstractReactiveEntitiesOperations.java
> -        if (!entities.iterator().hasNext()) {
I understand your objective. If we do it that way, there will be about 30 places in code wrapped with that if. From a design point of view, I would stick with my existing approach. I am not sure about the performance implications of my existing approach. But it seems like the "call with an empty list" use case is an edge case.

2022-10-05 08:27 UTC, merged

2022-10-05 08:27 UTC, dstepanov commented on data-runtime/src/main/java/io/micronaut/data/runtime/operations/internal/AbstractReactiveEntitiesOperations.java
> -        if (!entities.iterator().hasNext()) {
Ok. Thanks for the contribution!