Improve docs
micronaut-projects/micronaut-data pull request #2361
Opened 2023-07-12 14:36 UTC by dstepanov

My commit didn't got pushed and merged

2023-07-12 14:47 UTC, dstepanov commented on src/main/docs/guide/whatsNew.adoc
> +- Hibernate Reactive 6
Corrected

2023-07-13 08:08 UTC, sdelamo requested changes

2023-07-13 08:08 UTC, sdelamo commented on src/main/docs/guide/whatsNew.adoc
> +- Hibernate Reactive 2 (Hibernate 6 compatible)
```suggestion
- https://hibernate.org/reactive/releases/2.0/[Hibernate Reactive 2] (Hibernate 6 compatible)
```

2023-07-13 08:08 UTC, sdelamo commented on src/main/docs/guide/whatsNew.adoc
> +- Hibernate 6
```suggestion
- https://hibernate.org/orm/documentation/6.0/[Hibernate 6]
```

2023-07-13 08:08 UTC, sdelamo commented on src/main/docs/guide/breaks.adoc
> +Find all return type changed to be `List`
```suggestion
Find all return type changed to be `List` instead of `Iterable`
```

2023-07-13 16:04 UTC, merged