Testcontainers via test-resources version catalog
micronaut-projects/micronaut-data pull request #2777
Opened 2024-02-02 18:56 UTC by wetted

2024-02-05 10:30 UTC, sdelamo requested changes
Please, it is important not to change the Gradle configuration. These dependencies should be `testImplementation` not `implementation`.

2024-02-05 10:30 UTC, sdelamo commented on benchmarks/benchmark-spring-data-mongodb/build.gradle
> +    implementation(mnTestResources.testcontainers.mongodb)
```suggestion
    testImplementation(mnTestResources.testcontainers.mongodb)
```

2024-02-05 10:30 UTC, sdelamo commented on data-connection-jdbc/build.gradle
> +    implementation(mnTestResources.testcontainers.mysql)
```suggestion
    testImplementation(mnTestResources.testcontainers.mysql)
```

2024-02-05 10:30 UTC, sdelamo commented on data-connection-jdbc/build.gradle
> +    implementation(mnTestResources.testcontainers.mariadb)
```suggestion
    testImplementation(mnTestResources.testcontainers.mariadb)
```

2024-02-05 10:30 UTC, sdelamo commented on data-connection-jdbc/build.gradle
> +    implementation(mnTestResources.testcontainers.postgres)
```suggestion
    testImplementation(mnTestResources.testcontainers.postgres)
```

2024-02-05 10:30 UTC, sdelamo commented on data-connection-jdbc/build.gradle
> +    implementation(mnTestResources.testcontainers.mssql)
```suggestion
    testImplementation(mnTestResources.testcontainers.mssql)
```

2024-02-05 10:30 UTC, sdelamo commented on data-connection-jdbc/build.gradle
> +    implementation(mnTestResources.testcontainers.oracle.xe)
```suggestion
    testImplementation(mnTestResources.testcontainers.oracle.xe)
```

2024-02-05 10:30 UTC, sdelamo commented on data-jdbc/build.gradle
> +    implementation(mnTestResources.testcontainers.mysql)
```suggestion
    testImplementation(mnTestResources.testcontainers.mysql)
```

2024-02-05 10:30 UTC, sdelamo commented on data-jdbc/build.gradle
> +    implementation(mnTestResources.testcontainers.mariadb)
```suggestion
    testImplementation(mnTestResources.testcontainers.mariadb)
```

2024-02-05 10:30 UTC, sdelamo commented on data-jdbc/build.gradle
> +    implementation(mnTestResources.testcontainers.mssql)
```suggestion
    testImplementation(mnTestResources.testcontainers.mssql)
```

2024-02-05 10:30 UTC, sdelamo commented on data-r2dbc/build.gradle
> +    implementation(mnTestResources.testcontainers.r2dbc)
```suggestion
    testImplementation(mnTestResources.testcontainers.r2dbc)
```

2024-02-05 15:35 UTC, wetted commented
> Please, it is important not to change the Gradle configuration. These dependencies should be `testImplementation` not `implementation`.

Thanks for catching that. It was quite unintentional.

2024-02-07 08:49 UTC, sdelamo approved these changes

2024-02-07 08:49 UTC, merged