Support subquery Criteria API
micronaut-projects/micronaut-data pull request #3116
Opened 2024-09-10 14:07 UTC by dstepanov

First step to support pagination with JOINs

2024-09-10 19:08 UTC, graemerocher requested changes

2024-09-10 19:08 UTC, graemerocher commented on data-model/src/main/java/io/micronaut/data/model/jpa/criteria/PersistentEntitySubquery.java
> +public interface PersistentEntitySubquery<T> extends Subquery<T>, PersistentEntityCommonAbstractCriteria {
complete the javadoc for the public methods

2024-09-10 19:08 UTC, graemerocher commented on data-processor/src/main/java/io/micronaut/data/processor/visitors/RepositoryTypeElementVisitor.java
> +                e.printStackTrace();
should be removed or handled differently

2024-09-11 08:10 UTC, radovanradic approved these changes

2024-09-11 09:44 UTC, dstepanov commented on data-model/src/main/java/io/micronaut/data/model/jpa/criteria/PersistentEntitySubquery.java
> +public interface PersistentEntitySubquery<T> extends Subquery<T>, PersistentEntityCommonAbstractCriteria {
Added for new methods, for overriden the javadoc should be taken from the super interface.

2024-09-11 09:44 UTC, dstepanov commented on data-processor/src/main/java/io/micronaut/data/processor/visitors/RepositoryTypeElementVisitor.java
> +                e.printStackTrace();
Uninentialy added

2024-09-11 12:37 UTC, graemerocher approved these changes

2024-09-11 13:41 UTC, merged